import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const initialProperties = [
  {
    id: "p1",
    title: "Skyline Glass Penthouse over Central Park",
    type: "Buy",
    propertyType: "Penthouse",
    price: "$4,950,000",
    priceNum: 4950000,
    currency: "USD",
    country: "United States",
    countryCode: "US",
    city: "New York",
    location: "Manhattan, New York",
    beds: 4,
    baths: 4,
    area: 3800,
    tag: "Ultra Luxury",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 5,
    availableSlots: 2,
    discountPercent: 12,
    flashExpiresAt: new Date(Date.now() + 48 * 3600000),
    description: "Iconic floor-to-ceiling glass penthouse offering 360-degree Central Park and skyline views, private elevator, and wraparound terrace."
  },
  {
    id: "p2",
    title: "Mayfair Victorian Heritage Townhouse",
    type: "Buy",
    propertyType: "Villa",
    price: "£3,250,000",
    priceNum: 3250000,
    currency: "GBP",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    location: "Mayfair, London",
    beds: 4,
    baths: 3,
    area: 2950,
    tag: "Historic",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: false,
    description: "Period Victorian residence situated in prestigious Mayfair, boasting ornate cornicing, private mews garden, and wine cellar."
  },
  {
    id: "p3",
    title: "Palm Jumeirah Waterfront Villa with Private Beach",
    type: "Buy",
    propertyType: "Villa",
    price: "AED 12,800,000",
    priceNum: 12800000,
    currency: "AED",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    location: "Palm Jumeirah, Dubai",
    beds: 5,
    baths: 6,
    area: 6200,
    tag: "Waterfront",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 4,
    availableSlots: 1,
    discountPercent: 15,
    flashExpiresAt: new Date(Date.now() + 36 * 3600000),
    description: "Signature Palm beachfront villa with private infinity pool, direct Persian Gulf beach access, and state-of-the-art Italian kitchen."
  },
  {
    id: "p4",
    title: "Roppongi Hills High-Rise 2BHK Residence",
    type: "Buy",
    propertyType: "2BHK",
    price: "¥128,000,000",
    priceNum: 128000000,
    currency: "JPY",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    location: "Minato-ku, Tokyo",
    beds: 2,
    baths: 2,
    area: 1120,
    tag: "Panoramic View",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 6,
    availableSlots: 3,
    discountPercent: 10,
    flashExpiresAt: new Date(Date.now() + 64 * 3600000),
    description: "Ultra-modern Roppongi residence with Mount Fuji skyline vistas, 24-hour bilingual concierge, and membership to the exclusive sky spa."
  },
  {
    id: "p5",
    title: "Le Marais Designer 1BHK Haussmann Apartment",
    type: "Buy",
    propertyType: "1BHK",
    price: "€1,150,000",
    priceNum: 1150000,
    currency: "EUR",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    location: "4th Arrondissement, Paris",
    beds: 1,
    baths: 1,
    area: 720,
    tag: "Haussmannian",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Classic Haussmann-style apartment with herringbone parquet, marble fireplaces, cast iron balcony, and soaring 3.4-meter ceilings."
  },
  {
    id: "p6",
    title: "Marina Bay Sands View Executive 3BHK",
    type: "Buy",
    propertyType: "3BHK",
    price: "$2,650,000",
    priceNum: 2650000,
    currency: "USD",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    location: "Marina Bay, Singapore",
    beds: 3,
    baths: 3,
    area: 1850,
    tag: "Iconic View",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: false,
    description: "Prestigious Marina Bay residence with grand balcony facing Gardens by the Bay, private lift lobby, and smart biometric entry."
  },
  {
    id: "p7",
    title: "Bondi Coastal Haven 2BHK with Ocean Balcony",
    type: "Buy",
    propertyType: "2BHK",
    price: "$1,420,000",
    priceNum: 1420000,
    currency: "USD",
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    location: "Bondi Beach, Sydney",
    beds: 2,
    baths: 2,
    area: 1250,
    tag: "Oceanfront",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Sun-drenched beachside haven overlooking Bondi surf, European oak finishes, and short stroll to premier coastal cafes."
  },
  {
    id: "p8",
    title: "Sea-Facing Luxury 4BHK Penthouse",
    type: "Buy",
    propertyType: "4BHK+",
    price: "₹14.5 Cr",
    priceNum: 145000000,
    currency: "INR",
    country: "India",
    countryCode: "IN",
    city: "Mumbai",
    location: "Bandra West, Mumbai",
    beds: 4,
    baths: 5,
    area: 4100,
    tag: "Celebrity Enclave",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 3,
    availableSlots: 1,
    discountPercent: 8,
    flashExpiresAt: new Date(Date.now() + 28 * 3600000),
    description: "Lavish duplex penthouse in Bandra offering sweeping Arabian Sea views, private plunge pool, and dedicated 4-car parking bay."
  },
  {
    id: "p9",
    title: "Sunlit 3BHK near Besant Nagar Beach",
    type: "Buy",
    propertyType: "3BHK",
    price: "₹1.85 Cr",
    priceNum: 18500000,
    currency: "INR",
    country: "India",
    countryCode: "IN",
    city: "Chennai",
    location: "Besant Nagar, Chennai",
    beds: 3,
    baths: 3,
    area: 1650,
    tag: "Ready to move",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "East-facing 3-bedroom apartment with sea breeze, modular kitchen, covered car park, and round-the-clock security just 400m from Elliot's beach."
  },
  {
    id: "p10",
    title: "Lake Geneva Panoramic Villa & Vineyard",
    type: "Buy",
    propertyType: "Villa",
    price: "€7,800,000",
    priceNum: 7800000,
    currency: "EUR",
    country: "Switzerland",
    countryCode: "CH",
    city: "Geneva",
    location: "Cologny, Geneva",
    beds: 6,
    baths: 6,
    area: 7100,
    tag: "Alpine Luxury",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: false,
    description: "Spectacular Cologny estate overlooking Lake Geneva and Mont Blanc, complete with private vineyard, spa pavilion, and guest chalet."
  },
  {
    id: "p11",
    title: "Tribeca Minimalist Studio Loft",
    type: "Rent",
    propertyType: "Studio",
    price: "$3,800/mo",
    priceNum: 3800,
    currency: "USD",
    country: "United States",
    countryCode: "US",
    city: "New York",
    location: "Tribeca, New York",
    beds: 1,
    baths: 1,
    area: 650,
    tag: "High Ceilings",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Cast-iron historic building loft with exposed brick, 12ft timber-beamed ceilings, chef's galley kitchen, and key-locked elevator."
  },
  {
    id: "p12",
    title: "Kensington Garden 2BHK Serviced Residence",
    type: "Rent",
    propertyType: "2BHK",
    price: "£3,400/mo",
    priceNum: 3400,
    currency: "GBP",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    location: "Kensington, London",
    beds: 2,
    baths: 2,
    area: 1100,
    tag: "Furnished",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 8,
    availableSlots: 2,
    discountPercent: 20,
    flashExpiresAt: new Date(Date.now() + 52 * 3600000),
    description: "Superbly renovated 2BHK flat overlooking private communal gardens, featuring designer Italian furnishings and weekly housekeeping."
  },
  {
    id: "p13",
    title: "Downtown Dubai Burj View 1BHK Suite",
    type: "Rent",
    propertyType: "1BHK",
    price: "AED 9,500/mo",
    priceNum: 9500,
    currency: "AED",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    location: "Downtown, Dubai",
    beds: 1,
    baths: 1,
    area: 780,
    tag: "All Amenities",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Floor 42 suite with unobstructed front-row views of Burj Khalifa and Dubai Fountain, inclusive of rooftop pool and gym pass."
  },
  {
    id: "p14",
    title: "Shinjuku Modern Compact 1BHK",
    type: "Rent",
    propertyType: "1BHK",
    price: "¥210,000/mo",
    priceNum: 210000,
    currency: "JPY",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    location: "Shinjuku, Tokyo",
    beds: 1,
    baths: 1,
    area: 480,
    tag: "Near Metro",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Quiet designer corner apartment 4 mins walk from Shinjuku-sanchome Station. Built-in work desk, high-speed fiber internet, and auto-bath system."
  },
  {
    id: "p15",
    title: "Indiranagar Green Terrace 3BHK Villa",
    type: "Rent",
    propertyType: "3BHK",
    price: "₹65,000/mo",
    priceNum: 65000,
    currency: "INR",
    country: "India",
    countryCode: "IN",
    city: "Bangalore",
    location: "Indiranagar, Bangalore",
    beds: 3,
    baths: 3,
    area: 2100,
    tag: "Tech Corridor",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Tranquil tree-lined villa with private terrace garden, solar power backup, servant quarters, and fast access to 100ft Road dining."
  },
  {
    id: "p16",
    title: "Manhattan Corporate Executive Penthouse",
    type: "Lease",
    propertyType: "Penthouse",
    price: "$14,000/mo",
    priceNum: 14000,
    currency: "USD",
    country: "United States",
    countryCode: "US",
    city: "New York",
    location: "Midtown Manhattan, New York",
    beds: 3,
    baths: 3,
    area: 2600,
    leaseTerm: "2 to 5 Years",
    tag: "Corporate Lease",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: true,
    totalSlots: 5,
    availableSlots: 2,
    discountPercent: 15,
    flashExpiresAt: new Date(Date.now() + 40 * 3600000),
    description: "Turnkey executive penthouse designed for multinational corporate leases. Includes private meeting room, dedicated fiber link, and chauffeur parking."
  },
  {
    id: "p17",
    title: "Canary Wharf Diplomatic 3BHK Waterfront Suite",
    type: "Lease",
    propertyType: "3BHK",
    price: "£5,500/mo",
    priceNum: 5500,
    currency: "GBP",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    location: "Canary Wharf, London",
    beds: 3,
    baths: 3,
    area: 1900,
    leaseTerm: "1 to 3 Years",
    tag: "Long Term Lease",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Modern riverside duplex with panoramic River Thames vistas, 24h concierge, private health club, and secure underground double garage."
  },
  {
    id: "p18",
    title: "Dubai Hills Golf Club Luxury Estate Villa",
    type: "Lease",
    propertyType: "Villa",
    price: "AED 38,000/mo",
    priceNum: 38000,
    currency: "AED",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    location: "Dubai Hills, Dubai",
    beds: 5,
    baths: 5,
    area: 5400,
    leaseTerm: "2 to 5 Years",
    tag: "Golf Course View",
    status: "ACTIVE",
    isFeatured: true,
    isFlashOffer: false,
    description: "Exclusive golf fairway villa with infinity pool, smart climate control, staff quarters, and 18-hole championship golf club privileges."
  },
  {
    id: "p19",
    title: "Bandra Kurla Complex (BKC) Executive 2BHK",
    type: "Lease",
    propertyType: "2BHK",
    price: "₹1,40,000/mo",
    priceNum: 140000,
    currency: "INR",
    country: "India",
    countryCode: "IN",
    city: "Mumbai",
    location: "BKC, Mumbai",
    beds: 2,
    baths: 2,
    area: 1350,
    leaseTerm: "3 Years Fixed",
    tag: "Commercial Hub",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Spacious corner unit located right in the heart of Mumbai's premier financial hub. Complete business center and swimming pool amenities."
  },
  {
    id: "p20",
    title: "Omotesando Architectural Minimalist Studio",
    type: "Lease",
    propertyType: "Studio",
    price: "¥320,000/mo",
    priceNum: 320000,
    currency: "JPY",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    location: "Shibuya, Tokyo",
    beds: 1,
    baths: 1,
    area: 620,
    leaseTerm: "1 Year Renewable",
    tag: "Architectural Gem",
    status: "ACTIVE",
    isFeatured: false,
    isFlashOffer: false,
    description: "Custom architect-designed studio featuring fair-faced concrete, concealed storage walls, and premier boutique shopping at your doorstep."
  }
];

async function main() {
  console.log("Seeding database...");

  // Upsert demo user
  const demoUser = await prisma.user.upsert({
    where: { email: "demo@offhome.in" },
    update: {},
    create: {
      email: "demo@offhome.in",
      name: "Demo Owner",
      phone: "+91 98400 12345",
      verified: true,
      role: "USER"
    }
  });

  console.log(`Demo user ready: ${demoUser.email} (${demoUser.id})`);

  for (const prop of initialProperties) {
    await prisma.property.upsert({
      where: { id: prop.id },
      update: {
        ...prop,
        ownerId: demoUser.id
      },
      create: {
        ...prop,
        ownerId: demoUser.id
      }
    });
  }

  console.log(`Successfully seeded ${initialProperties.length} properties!`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
